include neutral exit code

diff --git a/.github/workflows/process-pr-merge.yml b/.github/workflows/process-pr-merge.yml
--- a/.github/workflows/process-pr-merge.yml
+++ b/.github/workflows/process-pr-merge.yml
@@ -38,7 +38,7 @@ jobs:
           if [ -z "$pr_number" ]; then
             echo "No PR associated with commit $commit_sha."
             echo "pr_number=" >> $GITHUB_OUTPUT
-            exit 0
+            exit 78  # Neutral exit code
           fi
 
           pr_body=$(gh api -X GET "repos/${{ github.repository }}/pulls/$pr_number" --jq '.body' | sed 's/\r//g')
