test template and release type changes

diff --git a/.github/workflows/update_changelog.yml b/.github/workflows/update_changelog.yml
--- a/.github/workflows/update_changelog.yml
+++ b/.github/workflows/update_changelog.yml
@@ -1,9 +1,9 @@
+name: update-changelog
+
 on:
   push:
     branches:
       - main
-
-name: update-changelog
 
 jobs:
   update-changelog:
@@ -19,8 +19,8 @@ jobs:
           token: ${{ secrets.ACTIONS_PAT }}
           fetch-depth: 0
       
-      - name: Extract changelog entry from PR
-        id: extract_changelog
+      - name: Extract release note from PR
+        id: extract_release_note
         run: |
           # Get the latest commit SHA
           commit_sha=$(git log -1 --format="%H")
@@ -37,13 +37,7 @@ jobs:
 
           # Get the PR body and extract release note
           pr_body=$(gh api -X GET "repos/${{ github.repository }}/pulls/$pr_number" --jq '.body' | sed 's/\r//g')
-          changelog_entry=$(echo "$pr_body" | awk 'BEGIN { found=0 } /```release-note/ { found=1; next } /```/ { found=0 } found { print }' | sed '/^$/d')
-
-          # Exit if no changelog entry found
-          if [ -z "$changelog_entry" ]; then
-            echo "No changelog entry found."
-            exit 0
-          fi
+          release_note=$(echo "$pr_body" | awk 'BEGIN { found=0 } /```release-note/ { found=1; next } /```/ { found=0 } found { print }' | sed '/^$/d')
 
           # Detect change type
           change_type=$(echo "$pr_body" | grep -oP '(?<=- \[x\] `)[A-Z]+(?=`)' | head -n 1)
@@ -58,7 +52,8 @@ jobs:
               section="### Fixed"
               ;;
             "OTHER")
-              section="### Miscellaneous"
+              echo "Change type is 'OTHER'. Skipping release note as it is not required."
+              exit 0
               ;;
             *)
               echo "Unknown change type: $change_type"
@@ -66,9 +61,15 @@ jobs:
               ;;
           esac
 
+          # Exit if no release note is found (only applicable for non-OTHER types)
+          if [ -z "$release_note" ]; then
+            echo "No release note found for change type: $change_type."
+            exit 1
+          fi
+
           # Store the extracted information in environment variables
           pr_url="https://github.com/${{ github.repository }}/pull/$pr_number"
-          echo "changelog=${changelog_entry} ($pr_url)" >> $GITHUB_ENV
+          echo "release_note=${release_note} ($pr_url)" >> $GITHUB_ENV
           echo "section=$section" >> $GITHUB_ENV
           echo "pr_number=$pr_number" >> $GITHUB_ENV
 
@@ -78,24 +79,21 @@ jobs:
           pr_body=$(gh api -X GET "repos/${{ github.repository }}/pulls/${{ env.pr_number }}" --jq '.body' | sed 's/\r//g')
           major_checked=$(echo "$pr_body" | grep -q '\[x\] `MAJOR`' && echo "true" || echo "false")
           minor_checked=$(echo "$pr_body" | grep -q '\[x\] `MINOR`' && echo "true" || echo "false")
-          patch_checked=$(echo "$pr_body" | grep -q '\[x\] `PATCH`' && echo "true" || echo "false")
+          wait_checked=$(echo "$pr_body" | grep -q '\[x\] `WAIT`' && echo "true" || echo "false")
 
           if [ "$major_checked" == "true" ]; then
             echo "BUMP_TYPE=major" >> $GITHUB_ENV
           elif [ "$minor_checked" == "true" ]; then
             echo "BUMP_TYPE=minor" >> $GITHUB_ENV
-          elif [ "$patch_checked" == "true" ]; then
-            echo "BUMP_TYPE=patch" >> $GITHUB_ENV
-          else
-            echo "No release bump required."
-            exit 0
+          elif [ "$wait_checked" == "true" ]; then
+            echo "WAIT was checked. No release required."
           fi
 
-      - name: Add entry to changelog
+      - name: Add release note to changelog
         if: env.pr_number != ''
         run: |
-          # Insert the changelog entry under the first matching section in Unreleased (avoids / delimeter to not conflict with url)
-          sed -i "0,/${{ env.section }}/s@${{ env.section }}@${{ env.section }}\n- ${{ env.changelog }}@" CHANGELOG.md
+          # Insert the release note under the first matching section in Unreleased
+          sed -i "0,/${{ env.section }}/s@${{ env.section }}@${{ env.section }}\n- ${{ env.release_note }}@" CHANGELOG.md
 
           # Show the updated changelog
           cat CHANGELOG.md
@@ -105,14 +103,14 @@ jobs:
         uses: EndBug/add-and-commit@v7
         with:
           add: 'CHANGELOG.md'
-          message: "Update CHANGELOG.md with entry from PR #${{ env.pr_number }}"
+          message: "Update CHANGELOG.md with release note from PR #${{ env.pr_number }}"
           author_email: git-action-bot@example.com
           author_name: Git Action Bot
           token: ${{ secrets.GITHUB_TOKEN }}
           push: true
 
       - name: Dispatch GitHub Release Action
-        if: env.BUMP_TYPE != '' # Ensures no action if NO RELEASE is selected
+        if: env.BUMP_TYPE != '' # Ensures no action if WAIT is selected
         run: |
           echo "Triggering release action with bump type: ${{ env.BUMP_TYPE }}"
           curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
